name: Prepare for Android
description: Prepares Android runtime (ie. installs java and sets everything up)
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        set -e
        sudo apt update -y
        sudo apt install -y python3-venv python3.10-venv git unzip
    - shell: bash
      run: |
        set -e
        refName=${{ github.ref_name }}
        refType=${{ github.ref_type }}
        if [ $refType = "branch" ]; then
          refName="$refName-SNAPSHOT"
        fi
        echo "VERSION_NAME=$refName" >> gradle.properties

    - shell: bash
      run: |
        set -e
        echo "GithubPassword=${{ github.token }}" >> gradle.properties
        echo "GithubUsername=${{ github.actor }}" >> gradle.properties

    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - uses: android-actions/setup-android@v3
