name: Prepare for JVM
description: Prepares JDK runtime (ie. installs java and sets everything up)
runs:
  using: composite
  steps:
    - uses: poin7less/actions/.github/actions/setup@master

    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
