name: AutoMerge

on:
  workflow_call:
    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  merge:
    runs-on: rapidash
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: poin7less/actions/.github/actions/github-cli@master
      - name: Merge
        run: gh pr merge --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTH_TOKEN }}
